config/routes.rb
Rekon::Application.routes.draw do
  get "home/index"

  root 'home#index'

  get 'earth' => 'earth#index'
  get 'results' => 'results#index', as: 'results'
  get 'finished' => 'finished#index', as: 'finished'

  get 'select-project/:id' => 'projects#select', as: 'select_project'

  resources :sections
  resources :prompts
  resources :replies

end

app/models/prompt.rb
# == Schema Information
#
# Table name: prompts
#
#  id                :integer          not null, primary key
#  section_id        :integer
#  sequence          :integer
#  type_of           :string(32)       default("text")
#  instructions      :text
#  suggested_answers :text
#  multi_response?   :boolean
#  dependencies      :text
#  created_at        :datetime
#  updated_at        :datetime
#  slug              :string(255)
#  details           :text
#  hint              :text
#  allow_other       :boolean

class Prompt < ActiveRecord::Base

  # relationships
  has_many :replies
  belongs_to :section

  serialize :suggested_answers
  serialize :dependencies

  # We may not want to have IDs... maybe slugs
  def prompt_ids_for_dependencies
    #hardcode for now
    d = [
      "p:a:*",
      "p:b:yes",
      "p:c:yes p:d:no AND"
    ]
    prompt_slugs = d.map{|x|x.scan(/p:\d+/)}
      .flatten
      .uniq
      .map{|x| x[2..-1]}

    Prompt.where("slug in (?)", prompt_slugs).pluck(:id)
  end

  def top_section
    if section.parent
      if section.parent.parent
        section.parent.parent
      else
        section.parent
      end
    else
      section
    end
  end

end

app/controllers/prompts_controller.rb
class PromptsController < ProjectBaseController

  include PromptRouter

  before_action :set_prompt, only: [:show, :update]

  def index
    @prompts = Prompt.all
    @replies = Hash[current_project.replies.where.not(complete:true).map{|r| [r.prompt.id, r]}]
    @next_prompt = next_prompt(current_project, current_project.flow.sections.first)
  end

  # GET /prompts/1
  # GET /prompts/1.json
  def show
    @top_section = @prompt.top_section
    @sub_section = @prompt.section
    set_replies(@prompt)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prompt
      @prompt = Prompt.find(params[:id])
      logger.fatal @prompt.replies.inspect
      #@prompt.replies = @prompt.replies.where(:prompt_id => @prompt.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prompt_params
      params.require(:prompt).permit(
        :id,
        replies: [
          :id,
          :answer,
          :skipped,
          :not_applicable
        ]
      )
    end

    # initialize at least (1) reply for prompt if not set
    def set_replies(prompt)
      if prompt.replies.length == 0
        @reply = prompt.replies.build
      else
        @reply = prompt.replies.last
      end
    end

end

app/helpers/prompt_helper.rb
module PromptHelper

  # generates proper inputs for the type of prompt
  def prompt_input_factory(form, type_of, answer, suggested_answers = false, hint = false, allow_other = false)
    html = '<div class="row">'

    if type_of == 'radio' || type_of == 'checkbox'
      html << prompt_radio_input(form, type_of == 'radio', answer, suggested_answers, allow_other)
    else
      html += '<div class="form-group col-xs-12">'
      if type_of == 'textarea'
        html += prompt_textarea(form, answer, hint)
      else
        html += prompt_text(form, answer, hint)
      end
      html += '</div>'
    end

    html << '</div>'
  end

  # genrates normal text prompt
  def prompt_text(form, answer, hint)
    form.text_field :answer, :class => 'form-control input-lg', :placeholder => hint
  end

  # generates prompt textarea
  def prompt_textarea(form, answer, hint)
    form.text_area :answer, :class => 'form-control', :placeholder => hint
  end

  # generates radio inputs
  def prompt_radio_input(form, is_radio, answer, suggested_answers, allow_other)
    html = ''
    has_answered = false

    suggested_answers.each_with_index do |suggestion, i|
      id = 'prompt_replies_answer_' + i.to_s
      checked = false
      if is_prompt_item_checked(true, answer, suggestion)
        has_answered = true
        checked = true
      elsif is_prompt_item_checked(false, answer, i)
        checked = true
      end

      html << '<div class="col-xs-12">'
      html << "<div class=\"prompt-radio radio\" title=\"#{suggestion}\">"
      html += render_prompt_item(form, is_radio, checked, id, is_radio ? suggestion : i)
      html << ' '
      html += form.label :answer, suggestion, :for => id

      html << '</div></div>'
    end

    if is_radio and allow_other
      html << '<div class="col-xs-12 col-sm-12 form-group">'
        html += form.text_field :answer_other, :class => 'form-control prompt-radio-other', :placeholder => 'Other',
          :value => has_answered ? '' : answer
      html << '</div>'
    end

    html
  end

  # renders individual radio/check boxes
  def render_prompt_item(form, is_radio, checked, id, value)
    html = ''
    if is_radio
      html += form.radio_button :answer, value, :id => id,
        :class => 'prompt-radio-input', :checked => checked
    else
      form.fields_for :answer, :index do |checkbox_form|
        html += checkbox_form.check_box value, :id => id,
          :class => 'prompt-radio-input', :checked => checked
      end
    end
    html.html_safe
  end

  # confirms whether or not radio/checkbox is checked by the value
  def is_prompt_item_checked(is_radio, answer, comparison = false)
    if is_radio && answer == comparison
      true
    elsif !is_radio && answer && answer.split('|')[comparison.to_i] == '1'
      true
    else
      false
    end
  end

end

app/views/prompts/index.html.haml
:css
  .no { color: red; }
  .yes { color: green; }
%h1 All Prompts

%pre=current_project.replies.to_json

%table.table
  %tr
    %th Section
    %th ID
    %th Instructions
    %th Complete
  -@prompts.each do |p|
    %tr
      %td=p.section.title
      %td=p.id
      %td=link_to p.instructions.html_safe, prompt_path(p)
      %td
        -if @replies[p.id]
          .yes
            Yup, #{@replies[p.id].answer}
        -else
          .no
            Nope

%h2 Replies
%pre=@replies.to_json

%h2 Next Prompt
%pre=@next_prompt.to_json

app/views/prompts/show.html.haml
-content_for :nav do
  =render 'sections/nav'

%h3.no-mt.prompt-instructions!= @prompt.instructions

%p.prompt-details!= @prompt.details

=form_for @reply do |form|
  =form.hidden_field :prompt_id
  =form.hidden_field :complete, value: true
  !=prompt_input_factory(form, @prompt.type_of, @prompt.replies.last.answer, @prompt.suggested_answers, @prompt.hint)
  -#.row
    .col-sm-3
      .checkbox.prompt-radio
        %label{ title: 'I don\'t want to answer this' }
          =form.check_box(:skipped)
          Skip?
    .col-sm-4
      .checkbox.prompt-radio
        %label{ title: 'This is not applicable to me' }
          =form.check_box(:not_applicable)
          Not Applicable?
  .row.mt-xx
    .col-xs-6
      =link_to section_path(@prompt.section_id), class: 'btn btn-default btn-lg' do
        =fa_icon 'chevron-circle-left'
        Back
    .col-xs-6.text-right
      %button.btn.btn-primary.btn-lg
        Continue
        =fa_icon 'chevron-circle-right'