config/routes.rb
Rekon::Application.routes.draw do
  get "home/index"

  root 'home#index'

  get 'earth' => 'earth#index'
  get 'results' => 'results#index', as: 'results'
  get 'finished' => 'finished#index', as: 'finished'

  get 'select-project/:id' => 'projects#select', as: 'select_project'

  resources :sections
  resources :prompts
  resources :replies

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "Timber"
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic", rel: "stylesheet", type: "text/css"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body.body-timber
    %nav.navbar.navbar-default.navbar-static-top.navbar-timber
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".header-nav-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.logo{href: root_url}
            =image_tag("logo-graphic.png")
        / Collect the nav links, forms, and other content for toggling
        .header-nav-collapse.collapse.navbar-collapse
          -#%ul.nav.navbar-nav
            %li
              =link_to "Sections", sections_path
            %li
              =link_to "Prompts", prompts_path
          %ul.nav.navbar-nav.navbar-right.navbar-top-timber
            -#if current_flow
              %li.navbar-text
                #{current_flow.title} :
                #{current_project.name}
            %li
              =link_to "#" do
                =fa_icon 'user'
                My Account
            %li
              =link_to results_path do
                =fa_icon 'list-alt'
                Results
            %li
              =link_to "#" do
                =fa_icon 'sign-out'
                Sign Out

    .container.body-container
      .row.content-container
        .col-xs-12
          -if content_for?(:nav)
            .row
              .col-sm-3.mb-x
                = yield :nav
              .col-sm-9
                = yield
          -else
            = yield


    %footer.footer
      .text-muted.text-center= 'Made by Dave, Nic & Jon'

    = render 'shared/minimap'

    = javascript_include_tag "application", "data-turbolinks-track" => true